### ISSUE TITLE
Project format?

### ISSUE THREAD

**Issue by theresaway** [pyunity/pyunity-gui#5]
When I open the editor, it says my folder isn't a valid project. The thing is, I don't know the project format. What is it?

**Comment by rayzchen** [comment]
Making a new project is a bit of a pain right now as I haven't made a GUI for that, though if you just open a python terminal and type:

```py
from pyunity import Loader
Loader.SaveAllScenes("Project")
```
This makes a blank project.

**Comment by rayzchen** [comment]
New code for this is:

```py
from pyunity import Loader
Loader.GenerateProject("Project")
```
