### ISSUE TITLE
How to create a project?

### ISSUE THREAD

**Issue by roman-smolnyk** [pyunity/pyunity-gui#6]
According to source code we need `*pyunity` files to use this editor, but how do I build such files? Does they need to be built or something else? Does there any simple example with the usage of this editor?

**Comment by rayzchen** [comment]
Running this will generate a project:

```py
from pyunity import SceneManager, Loader
SceneManager.AddScene("Scene")
Loader.GenerateProject("Test")
```

**Comment by rayzchen** [comment]
I am working on a GUI similar to Unity Hub that manages projects and whatnot, but in the meantime this is how you make projects. Replace "Test" with your project name, which generates a folder with all the required parts.

**Comment by roman-smolnyk** [comment]
But I got an error:

AttributeError: module 'pyunity.loader' has no attribute 'GenerateProject'

**Comment by rayzchen** [comment]
Install pyunity from the repo as described in the README.

**Comment by roman-smolnyk** [comment]
Fetched repo, started install.py file and got `No artifact found, check https://ci.appveyor.com/project/pyunity/pyunity for details` error... 

README contains no installation commands....

Unusable bugged piece of chocolate....

**Comment by rayzchen** [comment]
Use `cython=0 pip install git+https://github.com/pyunity/pyunity/archive/refs/heads/develop.zip` while `install.py` is fixed.

**Comment by rayzchen** [comment]
`install.py` fixed, tested on Windows with Python 3.10-x64 and x86.

**Comment by roman-smolnyk** [comment]
Trying to build example 10
```
SceneManager.AddScene(scene)
Loader.GenerateProject("Test")
```

ERROR:

`Loaded PyUnity version 0.9.0
Traceback (most recent call last):
  File "d:\Roman\Private\Projects\Python\unity-test\project\example\__init__.py", line 54, in <module>
    main()
  File "d:\Roman\Private\Projects\Python\unity-test\project\example\__init__.py", line 51, in main
    Loader.GenerateProject("Test")
  File "pyunity/loader.py", line 701, in pyunity.loader.GenerateProject
  File "pyunity/loader.py", line 706, in pyunity.loader.SaveProject
  File "pyunity/files.py", line 574, in pyunity.files.checkScene.inner
  File "pyunity/files.py", line 624, in pyunity.files.Project.ImportAsset
  File "pyunity/scenes/scene.py", line 77, in pyunity.scenes.scene.Scene.GetAssetFile
TypeError: unsupported operand type(s) for +: 'Scene' and 'str'`

**Comment by rayzchen** [comment]
You seem to be using an older version of PyUnity. Try and run `install.py` again?

**Comment by rayzchen** [comment]
Closing as no response made.

**Comment by rayzchen** [comment]
@poma23324 have you had any luck with running the editor? Please run `git pull`, `python install.py` and now you can run `python -m pyunity_editor -n Project`.

**Comment by roman-smolnyk** [comment]
I stopped exploring this project so I can't say you something about it now.
